---
name: Generate documentation

on:
  push:
    paths:
      - "proto/**"
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Update documentation
        run: make docker-docs-gen

      - name: Commit files
        run: |
          git config --local user.email "droplez@protonmail.com"
          git config --local user.name "droplez-proto"
          git add docs/proto_documentation.md
          git commit -m "documentation update"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
